//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayBinarySavedIamge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public int SNo { get; set; }
        public int RegistrationNo { get; set; }
        public string RegistrationCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Campus { get; set; }
        public string SectionCode { get; set; }
        public string CourseName { get; set; }
        public string Program { get; set; }
        public string Name { get; set; }
        public string Father_Husband_Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CNIC { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public byte[] Picture { get; set; }
        public string NoOfSibBro { get; set; }
        public string NoOfSibSis { get; set; }
        public string Nationality { get; set; }
        public string PlaceOfBirth { get; set; }
        public string CurrentResAddress { get; set; }
        public string PTCLNo { get; set; }
        public string CellNo1 { get; set; }
        public string CellNo2 { get; set; }
        public string Email { get; set; }
        public string OfficeAddress { get; set; }
        public string PABX { get; set; }
        public string Ext { get; set; }
        public string Tel_Dir { get; set; }
        public string RecStatus { get; set; }
        public string CreatedBy { get; set; }
    }
}
